spring:
  application:
    name: bookinline
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookinline}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto:
        validate
    show-sql: false
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            formate_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus, bookinline"
  endpoint:
    health:
        show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: Bookinline
    version: 1.0.0
    description: Bookinline is a web application for managing and booking properties.
