ALTER TABLE property ADD COLUMN city VARCHAR(255) NOT NULL DEFAULT 'Unknown';
ALTER TABLE property ADD COLUMN property_type VARCHAR(255) NOT NULL DEFAULT 'Unknown';
ALTER TABLE property ADD COLUMN floor_area INTEGER NOT NULL DEFAULT 0;
ALTER TABLE property ADD COLUMN bedrooms INTEGER NOT NULL DEFAULT 1;