ALTER TABLE property
    ADD COLUMN city VARCHAR(255) NOT NULL DEFAULT 'Unknown',
    ADD COLUMN property_type VARCHAR(255) NOT NULL DEFAULT 'Unknown',
    ADD COLUMN floor_area INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN bedrooms INTEGER NOT NULL DEFAULT 1;