name: CI - Dev Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  prod-build:
    runs-on: ubuntu-latest
    env:
        SPRING_PROFILE: prod
        POSTGRES_PROD_URL: jdbc:postgresql://localhost:5432/bookinline
        POSTGRES_PROD_USER: postgres
        POSTGRES_PROD_PASSWORD: password
        REDIS_PROD_HOST: redis
        REDIS_PROD_PORT: 6379
        REDIS_PROD_PASSWORD: password
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
        AWS_REGION: eu-north-1
        AWS_BUCKET: dummy

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bookinline
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:latest
        command: ["redis-server", "--requirepass", "password"]
        ports:
          - 6379:6379
              

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Docker Compose
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 20

      - name: Shutdown containers
        run: docker compose down
